
module.exports = {
  'test' : [
      // 'scsslint',
      'concat:test',
      'mochacli',
  ],
  'precompile-caniuse': [
    'json_to_sass:feature-border-radius',
    'json_to_sass:feature-css-boxshadow',
    'json_to_sass:feature-css-animation',
    'json_to_sass:feature-css-transitions',
    'json_to_sass:feature-transforms2d',
    'json_to_sass:feature-transforms3d',
    'json_to_sass:feature-css-gradients',
    'json_to_sass:feature-css3-boxsizing',
    'json_to_sass:feature-css-filters',
    'json_to_sass:feature-css-element-function',
    'json_to_sass:feature-multicolumn',
    'json_to_sass:feature-user-select-none',
    'json_to_sass:feature-flexbox',
    'json_to_sass:feature-calc',
    'json_to_sass:feature-background-img-opts',
    'json_to_sass:feature-font-feature',
    'json_to_sass:feature-border-image',
    'json_to_sass:feature-css-selection',
    'json_to_sass:feature-css-placeholder',
    'json_to_sass:feature-css-hyphens',
    'json_to_sass:feature-fullscreen',
    'json_to_sass:feature-css3-tabsize',
    'json_to_sass:feature-intrinsic-width',
    'json_to_sass:feature-css3-cursors-newer',
    'json_to_sass:feature-css-sticky',
    'json_to_sass:feature-pointer',
    'json_to_sass:feature-text-decoration',
    'json_to_sass:feature-text-size-adjust',
    'json_to_sass:feature-css-masks',
    'json_to_sass:feature-css-boxdecorationbreak',
    'json_to_sass:feature-object-fit',
    'json_to_sass:feature-css-shapes',
    'json_to_sass:feature-text-overflow',
    'json_to_sass:feature-text-emphasis',
    'json_to_sass:feature-css-deviceadaptation',
    'json_to_sass:feature-css-media-resolution',
    'json_to_sass:feature-css-text-align-last',
    'json_to_sass:feature-css-crisp-edges',
    'json_to_sass:feature-css-logical-props',
    'json_to_sass:feature-css-appearance',
    'json_to_sass:feature-css-snappoints',
    'json_to_sass:feature-css-regions',
    'json_to_sass:feature-css-image-set',
    'json_to_sass:feature-css-writing-mode',
    'json_to_sass:feature-css-cross-fade',
    'string-replace:precompiled'
      // 'json_to_sass:data',
  ],
  'default': [
      'test',
      'concat:dist',
      'sassdoc'
  ]
};
